### PR TITLE
profile schedule is the same as homepage schedule

### PR DESCRIPTION
**Pull request by natapokie**

### CODE REVIEW

**Review by jameskokoska — APPROVED** [review]
Looks good, but can it be tested?

**Comment by natapokie** [comment]
> Looks good, but can it be tested?

Sorry I should’ve tested it too, I’ll do that right now!!

**Comment by jameskokoska** [comment]
Not sure if it can be tested actually

**Comment by natapokie** [comment]
> @natapokie Can you go to an old commit, where the login wasn't hooked up to the Profile page, and test this Just so it can be merged safely

yep! I'll do that !

**Comment by natapokie** [comment]
in latest commit cac9630
- used the coloured accordion components according to the homepage, not sure if this looks good though so i can remove it too 😅 
- added canOpen prop to accordion
- disabled pointer events for accordions with no description

this is what the schedule component looks like in a previous commit (a4b3978), when the login page is not connected to the profile page, 
image

**Comment by jameskokoska** [comment]
Great thank you Natalie!

**Pull request merged**
