### PR TITLE
351 profile drop down

### PR DESCRIPTION
**Pull request by natapokie**
- [x] fix logout button
- [x] fix animations
- [x] add darkmode functionality --> click button to switch modes!

looks like this when logged in...
on desktop, 
image
on mobile, 
image
note: when logged in and registered, register will go away

when not logged in, 
image

### CODE REVIEW

**Comment by lukewarmtemp** [comment]
Not directly related to the profile page dropdown, but the weekdays are a little hard to see on the schedule on the home page and the profile page in dark mode. 
image
image

**Comment by lukewarmtemp** [comment]
The top corners might need to be rounded on the mobile view for the profile dropdown.
image

**Comment by natapokie** [comment]
> Not directly related to the profile page dropdown, but the weekdays are a little hard to see on the schedule on the home page and the profile page in dark mode. image image

ahh yep yep, I'll make sure to fix those in #413 👍👍 !

**Review by lukewarmtemp — CHANGES_REQUESTED** [review]
Only the tiny thing with the rounded corners on the profile dropdown mentioned above. Logout and dark mode toggle buttons work great and the profile drop-down animation looks good!

**Comment by natapokie** [comment]
> Only the tiny thing with the rounded corners on the profile dropdown mentioned above. Logout and dark mode toggle buttons work great and the profile drop-down animation looks good!

thanks for catching that luke!! fixed the border rounding in the latest commit 9502a3b
image

**Review by lukewarmtemp — APPROVED** [review]
LGTM!

**Review by jameskokoska — APPROVED** [review]
Looks great! I just did some minor tweaking

**Comment by natapokie** [comment]
@jameskokoska thanks james !!

**Pull request merged**
