### PR TITLE
added text input component

### PR DESCRIPTION
**Pull request by jameskokoska**
image

### CODE REVIEW

**Review by natapokie — APPROVED** [review]
looks good!! the animations with the textboxes look very very cool!

just one very small thing, it might be just formatting with storyboard though so let me know!
image
image
but the "heading/title" text for the required field is slightly higher than the regular textboxes

**Comment by Cali0707** [comment]
@jameskokoska ping me when you fix the headings for error text and I will review then

**Review by natapokie — APPROVED** [review]
looks good!

**Review by Cali0707 — APPROVED** [review]
LGTM 👍

**Pull request merged**
