### PR TITLE
adding coloured svg files to nav bar

### PR DESCRIPTION
**Pull request by natapokie**
related to #113 just on another branch! (i will fix #113 soon to make sure there are no conflicts!)

### CODE REVIEW

**Review by jameskokoska — APPROVED** [review]

**Comment by jameskokoska** [comment]
@natapokie please solve merge conflicts and I'll force merge

**Comment by natapokie** [comment]
> @natapokie please solve merge conflicts and I'll force merge

fixed the conflicts!

**Comment by jameskokoska** [comment]
@natapokie I still see some conflicts on my end :(

**Comment by natapokie** [comment]
> @natapokie I still see some conflicts on my end :(

Sorry @jameskokoska ! It's because I added the the new frosh logo, but it should be good now !

**Pull request merged**
