### PR TITLE
Added bursary request question to registration

### PR DESCRIPTION
**Pull request by MatthewGWilson**

### CODE REVIEW

**Review by Freeassassin — APPROVED** [review]
LGTM!

**Comment by jameskokoska** [comment]
This needs to be added to the backend frosh model
It already is in `paymentSchema` but shouldn't it also be added to `FroshSchema` if it is in the registration form page?

**Comment by Cali0707** [comment]
Yeah @jameskokoska ill push those backend changes tonight and then merge this

**Comment by jameskokoska** [comment]
Also I'd like to note it contradicts what Amy has said for bursary plans @MatthewGWilson 
image

**Comment by MatthewGWilson** [comment]
I talked to Amy about this the plan is to have a question on registration where they show interest in the bursary program and then we'll email all those students later this summer with the google form to apply for a bursary

**Comment by Cali0707** [comment]
@MatthewGWilson to clarify requirements here, all we need to do is store whether a suer wants to be emailed about bursary in our database, but charge everyone normally?

**Pull request merged**
