### PR TITLE
Updated About Us page w/ subcom photos

### PR DESCRIPTION
**Pull request by natapokie**
missing photos from the following subcoms (used a placeholder for now...)
- campus tours
- chillout cove
- sponsorship
- EDI

@MatthewGWilson would you be able to review these changes? thanks in advance !

Also made small changes to the profile containers (for tech team and subcoms), just to make them look nicer!
image

### CODE REVIEW

**Comment by jameskokoska** [comment]
Don't forget to compress images if you haven't already

**Comment by jameskokoska** [comment]
If you can also do https://github.com/UofT-Frosh-Orientation/orientation-website/issues/398 in this PR
It should be pretty simple

**Comment by natapokie** [comment]
> Don't forget to compress images if you haven't already

yep! images have been compressed, and lazy load added !

**Review by jameskokoska — APPROVED** [review]
I just resized the placeholder images to look like they have padding and added back in the hover scale animation

**Pull request merged**
