### PR TITLE
Added registration success screen

### PR DESCRIPTION
**Pull request by jameskokoska**
https://user-images.githubusercontent.com/50821962/173747752-12550bb7-75bd-41e8-b738-3908d0742d92.mp4

### CODE REVIEW

**Comment by jameskokoska** [comment]
As commented:
```js
// To get to this page you need to supply the state when routing
<Link state={{name: "James", froshGroup: "Lambda", froshGroupIcon: "λ"}} to={"/registration-success"}><ButtonOutlined label="Watch" isSecondary/></Link>
```

**Comment by jameskokoska** [comment]
https://user-images.githubusercontent.com/50821962/173758539-eb06d5ef-4bf6-4ccc-98ea-f24abc92fb59.mp4

**Review by natapokie — APPROVED** [review]
love the animations, they look so cool !!

(just fixed an extremely minor typo in my commit, just with "occurred" 😂)

**Comment by natapokie** [comment]
@jameskokoska also... i just wanted to ask if the "overlapping" outline like this is intentional?
image
if it's not intentional, let me know if there is anything i can do in illustrator to make it not overlap! i couldn't find which folder the lambda icon was in, but it might be because it's like two shapes...? 
but if it is intentional, it still looks really good regardless !!

**Comment by jameskokoska** [comment]
> love the animations, they look so cool !!
> 
> (just fixed an extremely minor typo in my commit, just with "occurred" 😂)

Thanks! My bad lol

**Comment by jameskokoska** [comment]
> @jameskokoska also... i just wanted to ask if the "overlapping" outline like this is intentional?
> image
> if it's not intentional, let me know if there is anything i can do in illustrator to make it not overlap! i couldn't find which folder the lambda icon was in, but it might be because it's like two shapes...? 
> but if it is intentional, it still looks really good regardless !!

The overlapping would be from the Inter font 
It's actually pretty cool, the animation is generated from the svg from the font file! 
So we don't need to add icons for every Frosh group

**Pull request merged**
