### PR TITLE
404 page

### PR DESCRIPTION
**Pull request by jameskokoska**
image

### CODE REVIEW

**Comment by jameskokoska** [comment]
@natapokie Could you make the bones show up better on desktop
i.e. make the graphic wider so it doesn't stretch therefore making stuff go off screen

You can also redo all the graphics as I don't know the copyright etc, I just removed the watermarks lol

**Review by Cali0707 — APPROVED** [review]
Very fun!!

**Review by natapokie — APPROVED** [review]
added more dino bones! the animations look great 🤩!!
image

**Comment by jameskokoska** [comment]
Yay looks way better now!!

**Pull request merged**
