### PR TITLE
Popup for FAQ Admin Confirm Delete

### PR DESCRIPTION
**Pull request by lukewarmtemp**
#471 
Clicking delete on a faq question will cause a pop-up to show with a cancel and delete button. Pressing the cancel button will cancel the delete and close the pop-up. Clicking delete will delete the question and close the pop-up.

URL at /faq-admin

### CODE REVIEW

**Comment by lukewarmtemp** [comment]
image

**Review by Freeassassin — CHANGES_REQUESTED** [review]
Everything looks good and the pop up comes up and the cancel button works properly but when I tried deleting a question both of the ones that I had submited got deleted.
image

**Comment by lukewarmtemp** [comment]
> Everything looks good and the pop up comes up and the cancel button works properly but when I tried deleting a question both of the ones that I had submited got deleted.

Ah good catch, I know what's wrong. Thanks!

**Review by Freeassassin — APPROVED** [review]
Looks great!

**Review by natapokie — APPROVED** [review]
looks great luke!! i just made the header font for the popup white!

**Pull request merged**
