### PR TITLE
Made dropdown component

### PR DESCRIPTION
**Pull request by Cali0707**
dropdown_1
dropdown_2
dropdown_3

### CODE REVIEW

**Review by jameskokoska — DISMISSED** [review]
Looks good! Maybe just use one of those icons and animate a 180 degree rotation
Might look smoother

**Review by natapokie — COMMENTED** [review]
looks good!! i agree with james, a rotation to the icon and maybe even adding a transition to the hover would look cool!

**Review by natapokie — DISMISSED** [review]
sorry, forgot to select approve!

**Review by jameskokoska — DISMISSED** [review]
Looks good!

**Review by jameskokoska — APPROVED** [review]

**Review by natapokie — APPROVED** [review]

**Pull request merged**
