### PR TITLE
277 dark mode

### PR DESCRIPTION
**Pull request by natapokie**
- [x] yellow with black text or yellow with white text... 🤔

to test dark mode use developer mode,
image

home page, 
image
image
image
image

about, 
imagefaq,

faq, 
image
image

profile,
image
image

register,
image
image
image

### CODE REVIEW

**Review by Freeassassin — CHANGES_REQUESTED** [review]
Looks great! I really love the dark purple aesthetic.

I just had one issue with the timeline component:

image

There is like a ghost outline of each day and the text is white on yellow so its not very readable.

But other than that  everything else looks amazing.

**Comment by jameskokoska** [comment]
Looks great Natalie, that didn't seem easy!
I would go for yellow with black text

**Comment by natapokie** [comment]
> There is like a ghost outline of each day and the text is white on yellow so its not very readable.

thanks for catching that farbod !!

**Comment by natapokie** [comment]
in latest commit 9a5c336

fixed timeline, was due to a stupid mistake because I misspelt the color name 😅
image

also made changed colours of login page dinos to match dark mode aesthetic,
image

**Review by Freeassassin — APPROVED** [review]
LGTM!

**Comment by jameskokoska** [comment]
Hi Natalie, just a small thing before I merge. Can you put the wave images to png. This is because png supports `object-fit: fill;` and these attributes should be applied to all the wave components to have a consistent height:
```css
.wave-image {
  width: 100vw;
  height: min(10vh, 80px);
  object-fit: fill;
  @include devices(tablet) {
    height: min(10vh, 40px);
  }
}
```

**Review by jameskokoska — APPROVED** [review]

**Pull request merged**
