### PR TITLE
Made Ask Question Button a Separate Component

### PR DESCRIPTION
**Pull request by lukewarmtemp**
- Cleaned up FAQ page code
- Moved Popup with the Ask Question form into a separate component
- Added the component to App.jsx to make the button show globally

### CODE REVIEW

**Comment by lukewarmtemp** [comment]
@jameskokoska When the user logs on, the ask question button also shows up on the register and profile page. Do we want this?

**Comment by lukewarmtemp** [comment]
Things to check for during QA:
- Ask question button is now on every page, not just the FAQ page
- Users are able to submit their questions successfully on every page and the data is stored in the database
- Clicking anywhere else on the screen, including the navbar should close the Ask Question popup if it's open

**Comment by jameskokoska** [comment]
> @jameskokoska When the user logs on, the ask question button also shows up on the register and profile page. Do we want this?

Yes all good, it should show up on all pages (logged in or not)

**Comment by jameskokoska** [comment]
- [ ] email stays after submitting question if logged in
- [ ] fixed states
- [ ] changed title
- [ ] added paragraph about email back
Just a few things: manage your state in the lowest level possible to avoid unnecessary rebuilds - especially when dealing in App.jsx
Global state, such as user, with redux should be accessed at the lowest level possible - since its a global state

**Comment by jameskokoska** [comment]
@natapokie let me know when you're done reviewing, but pull latest please

**Review by natapokie — APPROVED** [review]
looks good! i increased the z-index since the button was hiding on the login page, 
image

**Comment by natapokie** [comment]
> @natapokie let me know when you're done reviewing, but pull latest please

@jameskokoska done reviewing!

**Comment by jameskokoska** [comment]
Great thanks @lukewarmtemp and @natapokie for helping out so quickly!

**Pull request merged**
