### PR TITLE
285 about us section for tech team subcoms and hls

### PR DESCRIPTION
**Pull request by natapokie**
@MatthewGWilson if you could quickly check over the about us page that would be great!

todo:
- [ ] get edited photos of subcoms from photography 
- [ ] get a short description from each subcom to say what their role is in frosh week (@MatthewGWilson if i can get your help on that that would be amazing :)) )
  - [ ] also maybe the discipline of each subcom co-chair as well? (also need your help on this too Matt)
- [x] need photo from farbod, and tech team section complete !
- [ ] [for later] after tech team photo session, add in group photo to tech team section (?)

added sections for tech team, subcoms and hls!
image

tech team has a special section with photos and quotes
image

subcoms organized according to the category
image
for an example... of a "filled" subcom bubble,
image

finally hl page looks like this... added some animation to names too!
image

### CODE REVIEW

**Comment by MatthewGWilson** [comment]
Hey Natalie this looks amazing, great job! I'll try and get the subcom and HL info asap for you but I don't think there's any way I get it by launch so would it be possible to have this go up with only the exec and tech team tabs first and we put the subcom and HL tabs up once we have the info for them?

**Comment by natapokie** [comment]
> Hey Natalie this looks amazing, great job! I'll try and get the subcom and HL info asap for you but I don't think there's any way I get it by launch so would it be possible to have this go up with only the exec and tech team tabs first and we put the subcom and HL tabs up once we have the info for them?

Yep, for sure !

**Comment by Cali0707** [comment]
@natapokie add yourself to the about year page for tech team!!!

**Comment by natapokie** [comment]
> @natapokie add yourself to the about year page for tech team!!!

no it's gonna mess up the grid !! 😂😂 it looks perfect right now with 3x2 !

**Comment by MatthewGWilson** [comment]
Oh yes I'm sorry I didn't even notice you weren't there already because I just assumed you would be! Calum is right Natalie you need to be on there for sure!

**Comment by Cali0707** [comment]
> > @natapokie add yourself to the about year page for tech team!!!
> 
> no it's gonna mess up the grid !! 😂😂 it looks perfect right now with 3x2 !

That’s okay - just put someone in the bottom row. Much better to have you in there than to have a perfect grid.

**Comment by MatthewGWilson** [comment]
You could put yourself just below the grid with a fancy title too if you want something like Tech Team Content Creation Lead idk you have freedom to name your own role

**Comment by natapokie** [comment]
ahhhh 😭 thanks calum and matt, i'll add myself soon then !

**Review by MatthewGWilson — APPROVED** [review]
Idk about the code but it looks beautiful!

**Comment by MatthewGWilson** [comment]
@natapokie Apologies for the delay, here's the info for all the HLs and Subcoms https://docs.google.com/spreadsheets/d/1SkuHRKWlmUajmTbHV2Vw-a5zKMQ9CIbpkVSJZcY4CHQ/edit?usp=sharing

**Pull request merged**
