### PR TITLE
374 scunt leaderboard team points

### PR DESCRIPTION
**Pull request by natapokie**
- [ ] need to get leaderboard info from backend

on desktop, 
image

full screen, 
image

on mobile, 
image

### CODE REVIEW

**Review by Freeassassin — APPROVED** [review]
LGTM!

**Comment by jameskokoska** [comment]
Hi Natalie, just added some staggered animations using the power of SCSS!

https://user-images.githubusercontent.com/50821962/183808481-95f8e9b0-29b0-45c3-afb0-4fbe580e8b45.mp4

**Comment by jameskokoska** [comment]
Thanks for doing this, looks really polished!

**Review by jameskokoska — APPROVED** [review]
Great job!

**Comment by natapokie** [comment]
@jameskokoska the staggered animations look so cool!!! thanks for adding that in!!! 🤩

**Pull request merged**
