### PR TITLE
updating info for retreat

### LINKED ISSUE #663: Update Retreat Information
## **Changes:**

Describe the visual changed required.

## **Visuals:**

Update retreat information

## **Requirements:**

- [x] Need an updated waiver for retreat
- [ ] **Update number of tickets -> docker file RETREAT_MAX_TICKETS=80**
- [x] Nat and Farbod to move retreat above scunt and change the wording, instead of "Learn More" change to "Buy Now"
- [x] Highlight retreat somehow (so people know they need to pay) - either animation bubble or different color

## **External Factors:**

Describe any external requirements that might effect the issue (e.g need to await information from other party).

## **Related Issues/PRs:**

Link any other issue or PR that might be related to this issue.

## **Resources:**

Link any resources or people that might be helpful in the accomplishment of the issue.

### **Tutorials:**

- [Link 1]()
- [Link 2]()
- [Link 3]()

### **Documentation:**

- [Link 1]()
- [Link 2]()
- [Link 3]()

### PR DESCRIPTION
**Pull request by natapokie**
### **Issue:**

Closes # 

### **Accomplishments:**

- updating blurbs, adding pdf waiver

### **Visuals:** 

Any related visuals.

### **Expected Behavior:**

- behaviour 1
- behaviour 2
- behaviour 3

### **Testing Steps:**

Steps required to get expected behavior.

- step 1
- step 2
- step 3

### **Complications:**

- complication 1
- complication 2
- complication 3

### **Resources:**

Any additional resources used outside this in issue.

- resource 1
- resource 2
- resource 3

### CODE REVIEW

**Review by Sherryzh0830 — COMMENTED** [review]
Components work well in both light/dark modes! The video on the /frosh-retreat page plays as soon as the page is loaded, and the waiver can be downloaded smoothly. 
One small thing I was unsure about is these two lines on the very bottom of the page. Is there supposed to be a checkbox or confirming button here? (Also I don't really understand the 2nd sentence, might be missing brackets?)
Screen Shot 2023-07-09 at 3 30 50 PM

**Review by uzFer — APPROVED** [review]
Looks great, the PDF and video links all work perfectly on my end. I see this at the bottom of the page as well. Adding onto what Sherry said, if you'd want to change the statement to be clearer, we could try "By pressing 'Yes', you or a guardian (if you are under...)"?

image

**Comment by natapokie** [comment]
@Sherryzh0830 @uzFer thanks for bringing that up! i did copy whatever retreat gave us, but yes i agree that's pretty confusing now that I'm reading it a second time! will make some edits to that, thanks again 🙌

**Review by Freeassassin — APPROVED** [review]
Looks great!

**Pull request merged**
